name: lint actions
on:
  push:

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/che
        - name: Download actionlint
          id: get_actionlint
          run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
          shell: bash
        - name: Check workflow files
          run: ${{ steps.get_actionlint.outputs.executable }} -color
          shell: bash