name: Dynamic matrix
on: push
jobs:
    prepare:
        runs-on: ubuntu-latest
        steps:
        - id: dynamic
          run: | 
            json='{"name": ["bob", "alice"]}'
            echo "json=${json}" >> "${GITHUB_OUTPUT}"
        outputs: 
            matrix-json: ${{ steps.dynamic.outputs.json }}
    print:
        needs: [prepare]
        strategy:
            matrix: ${{ fromJSON(needs.prepare.outputs.matrix-json) }}
        runs-on: ubuntu-latest
        steps:
            - name: print name
              run: echo "${NAME}"
              env:
                  NAME: ${{ matrix.name }}
