name: fetch dependabot metadata
on: 
    pull_request:
        
jobs:
    fetch:
        if: ${{ github.actor == 'dependabot[bot]' }}
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
            - name: fetch dependabot metadata
              id: meta
              uses: dependabot/fetch-metadata@ffa630c65fa7e0ecfa0625b5ceda64399aea1b36 # v3
              with:
                github-token: "${{ secrets.GITHUB_TOKEN }}"
            - name: print metadata
              run: |
                echo "${UPDATE_TYPE}"
              env:
                UPDATE_TYPE: ${{ steps.meta.outputs.update-type}}
            