name: log group

on:
  push:
    branches:
      - main

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: show log group2
        run: |
          echo "::group::Show environment variables"
          printenv
          echo "::endgroup::"
          echo "::group::Greet"
          echo "hello world"
          echo "::endgroup::"
        env:
          TEST: "test"
